Feature/ts2 106 implement unit tests for supported ops
uktrade/help-desk-service pull request #10
Opened 2023-06-21 12:09 UTC by nikosbalta

2023-06-22 08:21 UTC, NickFitz commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
As these are the arguments used to make the request, rather than the request itself, `request_args` or something like that might be a better name.

2023-06-22 08:21 UTC, NickFitz commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
Same as for the equivalent line above.

2023-06-22 08:21 UTC, NickFitz commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
In fact, it might be better to unpack the arguments into several variables:

`request, subdomain, email, token = proxy_zendesk.call_args[0]`

as that will make the assertions below clearer without needing a comment to explain what they are.

2023-06-22 08:28 UTC, nikosbalta commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
I agree and apply the changes.

2023-06-22 08:34 UTC, nikosbalta commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
Agree

2023-06-22 08:37 UTC, nikosbalta commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
Agree as above

2023-06-22 10:15 UTC, rossmiller commented on tests/zendesk_api_proxy/test_supported_operations.py
Let's use pytest parametrize for all relevant URLs:

    """
    zenpy.Zenpy.tickets.create - POST /api/v2/tickets
    zenpy.Zenpy.tickets - GET /api/v2/tickets/{id}
    zenpy.Zenpy.tickets.comments - GET /api/v2/tickets/{id}/comments
    zenpy.Zenpy.users - GET /api/v2/users/{id}
    zenpy.Zenpy.users.create_or_update - POST /api/v2/users/create_or_update
    zenpy.Zenpy.users.me - GET /api/v2/users/me
    """
    
    @pytest.mark.parametrize("url, ...", [
        (reverse("api:ticket", kwargs={"id": 123}), ...),
        (...),
        (...),
    ])
    @mock.patch("zendesk_api_proxy.middleware.proxy_zendesk")
    def test_ticket_get_endpoint(
        self,
        proxy_zendesk: mock.MagicMock,
        client: Client,
        zendesk_required_settings,  # fixture: see /tests/conftest.py
        zendesk_creds_only,
        zendesk_authorization_header,
    ):
        response = Response()
        response._content = b"{}"
        response.status_code = HTTPStatus.OK

        proxy_zendesk.return_value = response
        client.get(url, headers={"Authorization": zendesk_authorization_header})
        proxy_zendesk.assert_called_once()

        request_obj, subdomain, email, *_ = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk

        assert request_obj.get_full_path() == url
        assert request_obj.method == "GET"
        assert subdomain == zendesk_creds_only.zendesk_subdomain
        assert email == zendesk_creds_only.zendesk_email

    @pytest.mark.parametrize("url, ...", [
        (reverse("api:ticket", kwargs={"id": 123}), ...),
        (...),
        (...),
    ])
    @mock.patch("zendesk_api_proxy.middleware.proxy_zendesk")
    def test_ticket_post_endpoint(
        self,
        proxy_zendesk: mock.MagicMock,
        client: Client,
        zendesk_required_settings,  # fixture: see /tests/conftest.py
        zendesk_creds_only,
        zendesk_authorization_header,
    ):
        response = Response()
        response._content = b"{}"
        response.status_code = HTTPStatus.OK

        proxy_zendesk.return_value = response
        client.get(url, headers={"Authorization": zendesk_authorization_header})
        proxy_zendesk.assert_called_once()

        request_obj, subdomain, email, *_ = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk

        assert request_obj.get_full_path() == url
        assert request_obj.method == "GET"
        assert subdomain == zendesk_creds_only.zendesk_subdomain
        assert email == zendesk_creds_only.zendesk_email

2023-06-22 10:15 UTC, rossmiller requested changes
Looks good (see parametrize comment). Can we also get a test for the has_endpoint function please?

2023-06-22 10:20 UTC, rossmiller commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
Regarding has_endpoint:

def has_endpoint(path, method):
    view_class = None

    for url_pattern in api_url_patterns:
        if url_pattern.pattern.match(path.replace("/api/", "")):
            view_class = url_pattern.lookup_str

    if not view_class:
        return False

    for class_name, obj in inspect.getmembers(sys.modules["help_desk_api.views"]):
        try:
            if issubclass(obj, APIView):
                if class_name in view_class:
                    if method in obj().allowed_methods:
                        return True
        except TypeError:
            pass

    return False
    
    could be broken into 2 functions - one for finding the view class and one for checking if the method is supported.
    
    That way, your tests can focus on the discrete logic in each function. The tests should demonstrate happy and unhappy paths through the logic (happy seed value, unhappy seed value).

2023-06-22 10:21 UTC, rossmiller commented on tests/zendesk_api_proxy/test_supported_operations.py
> +        request = proxy_zendesk.call_args[0]  # args passed to proxy_zendesk
2 functions, 2 tests per function (4 in total)

2023-06-22 12:21 UTC, nikosbalta commented on tests/zendesk_api_proxy/test_supported_operations.py
This enables to test different GET scenarios using the 
@pytest.mark.parametrize decorator

2023-06-23 11:52 UTC, nikosbalta commented on tests/zendesk_api_proxy/test_supported_operations.py
This has been completed

2023-06-28 08:18 UTC, NickFitz commented on zendesk_api_proxy/middleware.py
> +        #supported_endpoint = has_endpoint(request.path, request.method.upper())
Can get rid of this commented-out old version of the line 🙂

2023-06-28 08:25 UTC, NickFitz requested changes
Just the one commented-out line that needs removing, I think 🙂 

I was thinking about our chat yesterday concerning tests for the get and create ticket operations under conditions that would cause them to fail. I don't think that's necessary as part of this ticket, as we have another ticket to do with HTTP error conditions and I feel it would be more appropriate for those tests to be added as part of that, as until that's done, we won't really be sure how the components are supposed to raise errors and thus won't know if they're doing so correctly.

2023-06-28 09:57 UTC, nikosbalta commented on zendesk_api_proxy/middleware.py
> +        #supported_endpoint = has_endpoint(request.path, request.method.upper())
Yes is done

2023-06-28 10:50 UTC, NickFitz approved these changes

2023-06-28 11:19 UTC, nikosbalta commented
Ticket TS2-106 providing unit tests for Zendesk proxy

2023-06-28 11:20 UTC, merged